export const ADD_ITEM = 'ADD_ITEM';
export const EXIT = 'EXIT';
export const DATA_PAGE_RECOR_INPUT = 'DATA_PAGE_RECOR_INPUT';
export const DATA_DROPDOWN_WORKORDERCODE = 'DATA_DROPDOWN_WORKORDERCODE';
export const DATA_DROPDOWN_COLOR = 'DATA_DROPDOWN_COLOR';
export const DATA_DROPDOWN_SUBCODE = 'DATA_DROPDOWN_SUBCODE';
export const DATA_DROPDOWN_SEASON = 'DATA_DROPDOWN_SEASON';
export const DATA_DROPDOWN_MARKET = 'DATA_DROPDOWN_MARKET';
export const DATA_DROPDOWN_SIZE = 'DATA_DROPDOWN_SIZE';
export const SET_DATA_USER_INFO = 'SET_DATA_USER_INFO';
export const SET_DEFAULT_SCAN = 'SET_DEFAULT_SCAN';






